//! Rust port of [`@coralstack/cmd-ipc`](https://github.com/CoralStack/cmd-ipc).
//!
//! The wire protocol is byte-identical to the TypeScript library, so Rust
//! and Node.js processes can exchange commands over any channel that
//! carries JSON.
//!
//! This crate is runtime-agnostic: it depends on the `futures` primitives
//! only, and does not pull in tokio, async-std, or smol. Users drive the
//! per-channel pump future returned by `CommandRegistry::register_channel`
//! with the executor of their choice.
//!
//! See [`message`] for the wire format, [`ttl_map`] for the storage
//! primitive shared by the registry's reply/route/event tables, and
//! [`macro@command`] / [`macro@commands`] for the attribute macros that
//! let you register commands next to the code that implements them.

pub mod channel;
pub mod command;
pub mod error;
pub mod message;
pub mod registry;
pub mod schema;
pub mod ttl_map;

pub use channel::{CommandChannel, InMemoryChannel};
pub use command::Command;
pub use error::{ChannelError, CommandError, ExecuteErrorCode, RegisterErrorCode};
pub use message::{
    CommandDef, CommandSchema, ExecuteError, ExecuteResult, False, Message, MessageId,
    RegisterResult, True,
};
pub use registry::{CommandRegistry, Config};

// Internal helper used by the `#[commands]` macro; not part of the
// public API despite being re-exported at the crate root so generated
// code can name it.
#[doc(hidden)]
pub use registry::__handler_for_command;
pub use schema::normalize_schema;
pub use ttl_map::TtlMap;

// Re-exports for use by code generated by the `#[command]` / `#[commands]`
// macros. Users should not reference these directly; they're here so
// generated code can name stable paths even if the user's crate doesn't
// list these deps individually.
pub use coralstack_cmd_ipc_macros::{command, commands};
pub use schemars;
pub use serde_json;

/// Curated re-exports for the common public API.
///
/// ```ignore
/// use coralstack_cmd_ipc::prelude::*;
/// ```
pub mod prelude {
    pub use crate::{
        command, commands, ChannelError, Command, CommandChannel, CommandDef, CommandError,
        CommandRegistry, CommandSchema, Config, InMemoryChannel,
    };
}
