//! Rust port of [`@coralstack/cmd-ipc`](https://github.com/CoralStack/cmd-ipc).
//!
//! The wire protocol is byte-identical to the TypeScript library, so Rust
//! and Node.js processes can exchange commands over any channel that
//! carries JSON.
//!
//! This crate is runtime-agnostic: it depends on the `futures` primitives
//! only, and does not pull in tokio, async-std, or smol. Users drive the
//! per-channel pump future returned by `CommandRegistry::register_channel`
//! with the executor of their choice.
//!
//! See [`message`] for the wire format, [`ttl_map`] for the storage
//! primitive shared by the registry's reply/route/event tables, and
//! [`macro@command`] / [`macro@command_service`] for the attribute macros that
//! let you register commands next to the code that implements them.

pub mod channel;
pub mod command;
pub mod error;
pub mod event;
pub mod message;
pub mod registry;
pub mod schema;
pub mod ttl_map;

pub use channel::{CommandChannel, InMemoryChannel};
pub use command::{Command, DynCommand};
pub use error::{ChannelError, CommandError, ExecuteErrorCode, RegisterErrorCode};
pub use event::{DynEvent, Event};
pub use message::{
    CommandDef, CommandSchema, ExecuteError, ExecuteResult, False, Message, MessageId,
    RegisterResult, True,
};
pub use registry::{CommandRegistry, Config};

pub use schema::normalize_schema;
pub use ttl_map::TtlMap;

// Re-exports for use by code generated by the `#[command]` / `#[commands]`
// macros. Users should not reference these directly; they're here so
// generated code can name stable paths even if the user's crate doesn't
// list these deps individually.
pub use coralstack_cmd_ipc_macros::{command, command_service, event};
pub use schemars;
pub use serde_json;

/// Curated re-exports for the common public API.
///
/// ```ignore
/// use coralstack_cmd_ipc::prelude::*;
/// ```
pub mod prelude {
    pub use crate::{
        command, command_service, event, ChannelError, Command, CommandChannel, CommandDef,
        CommandError, CommandRegistry, CommandSchema, Config, DynCommand, DynEvent, Event,
        InMemoryChannel,
    };
}
