import 'reflect-metadata'

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'

import { CommandRegistry, HTTPChannel, registerCommands } from '@coralstack/cmd-ipc'

import App from './App'
import { CommandSchema } from './schemas'
import { ArrayService, StringService } from './services'

import './styles.css'

/**
 * Initialize the CommandRegistry with both local and remote commands
 *
 * The remote schema is generated by running:
 *   yarn generate-schema
 *
 * This fetches the command definitions from the worker and generates
 * a TypeScript file with full type safety.
 */
async function initializeRegistry() {
  // Create registry with merged schemas (local + remote)
  const registry = new CommandRegistry({
    id: 'frontend',
    schemas: { commands: CommandSchema },
  })

  // Register local command handlers (these run in the browser)
  registerCommands([StringService, ArrayService], registry)

  // Connect to Cloudflare Worker via HTTPChannel (client mode)
  const channel = new HTTPChannel({
    id: 'cf-worker',
    baseUrl: 'http://localhost:8787',
    commandPrefix: 'cloud', // Remote commands prefixed with 'cloud.'
    timeout: 30000,
  })

  await registry.registerChannel(channel)

  return registry
}

// Initialize and render the React app
initializeRegistry()
  .then((registry) => {
    createRoot(document.getElementById('root')!).render(
      <StrictMode>
        <App registry={registry} />
      </StrictMode>,
    )
  })
  .catch((error) => {
    // eslint-disable-next-line no-console
    console.error('Failed to initialize registry:', error)
    // Render error state
    createRoot(document.getElementById('root')!).render(
      <StrictMode>
        <div className="app">
          <header>
            <h1>cmd-ipc Cloudflare Worker Demo</h1>
          </header>
          <main className="error-container">
            <h2>Connection Error</h2>
            <p>Could not connect to the Cloudflare Worker at http://localhost:8787</p>
            <p>Make sure the worker is running:</p>
            <pre>yarn dev:worker</pre>
            <p>Then generate the schema:</p>
            <pre>yarn generate-schema</pre>
            <p>Error: {error.message}</p>
          </main>
        </div>
      </StrictMode>,
    )
  })
