import { existsSync, mkdirSync, readFileSync, rmSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'

import type { ICommandDefinitionBase } from '../../registry'
import type { SchemaDoc } from '../../schemas'
import { generateSchema } from './command'
import type { JsonSchema } from './schema-converter'

// Mock fetch globally
const mockFetch = vi.fn()
vi.stubGlobal('fetch', mockFetch)

// Helper to cast test objects to JsonSchema (StandardJsonSchema is a branded type)
const schema = <T>(obj: T): JsonSchema => obj as JsonSchema

// Helper to create a valid SchemaDoc response (as returned by GET /cmds.json)
function createSchemaDoc(commands: ICommandDefinitionBase[]): SchemaDoc {
  return {
    cmdschema: '1.0.0',
    commands,
  }
}

describe('generateSchema', () => {
  const testDir = join(tmpdir(), 'cmd-ipc-test-' + Date.now())
  const outputPath = join(testDir, 'generated-schema.ts')

  beforeEach(() => {
    vi.clearAllMocks()
    mkdirSync(testDir, { recursive: true })
  })

  afterEach(() => {
    if (existsSync(testDir)) {
      rmSync(testDir, { recursive: true, force: true })
    }
  })

  it('should generate schema file from remote commands', async () => {
    const mockCommands: ICommandDefinitionBase[] = [
      {
        id: 'user.create',
        description: 'Create a new user',
        schema: {
          request: schema({
            type: 'object',
            properties: {
              name: { type: 'string' },
              email: { type: 'string', format: 'email' },
            },
            required: ['name', 'email'],
          }),
          response: schema({
            type: 'object',
            properties: {
              id: { type: 'string' },
              success: { type: 'boolean' },
            },
            required: ['id', 'success'],
          }),
        },
      },
      {
        id: 'user.get',
        description: 'Get user by ID',
        schema: {
          request: schema({
            type: 'object',
            properties: {
              id: { type: 'string' },
            },
            required: ['id'],
          }),
          response: schema({
            type: 'object',
            properties: {
              name: { type: 'string' },
              email: { type: 'string' },
            },
            required: ['name', 'email'],
          }),
        },
      },
    ]

    mockFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(createSchemaDoc(mockCommands)),
    })

    await generateSchema({
      host: 'https://api.example.com',
      output: outputPath,
    })

    expect(existsSync(outputPath)).toBe(true)

    const content = readFileSync(outputPath, 'utf-8')

    // Check header
    expect(content).toContain('// Auto-generated by cmd-ipc CLI - DO NOT EDIT')
    expect(content).toContain('// Generated from: https://api.example.com/cmds.json')

    // Check imports
    expect(content).toContain("import * as v from 'valibot'")
    expect(content).toContain("import type { CommandSchemaMap } from '@coralstack/cmd-ipc'")

    // Check schema name (no prefix = RemoteCommandSchema)
    expect(content).toContain('export const RemoteCommandSchema = {')

    // Check commands
    expect(content).toContain("'user.create': {")
    expect(content).toContain('description: "Create a new user"')
    expect(content).toContain("'user.get': {")

    // Check satisfies
    expect(content).toContain('} as const satisfies CommandSchemaMap')
  })

  it('should apply prefix to command IDs', async () => {
    mockFetch.mockResolvedValue({
      ok: true,
      json: () =>
        Promise.resolve(
          createSchemaDoc([
            {
              id: 'user.create',
              description: 'Create a user',
            },
          ]),
        ),
    })

    await generateSchema({
      host: 'https://api.example.com',
      output: outputPath,
      prefix: 'cloud',
    })

    const content = readFileSync(outputPath, 'utf-8')

    // Check schema name with prefix
    expect(content).toContain('export const CloudCommandSchema = {')

    // Check command ID has prefix
    expect(content).toContain("'cloud.user.create': {")
  })

  it('should convert prefix to PascalCase for schema name', async () => {
    mockFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(createSchemaDoc([])),
    })

    await generateSchema({
      host: 'https://api.example.com',
      output: outputPath,
      prefix: 'my-api',
    })

    const content = readFileSync(outputPath, 'utf-8')
    expect(content).toContain('export const MyApiCommandSchema = {')
  })

  it('should create output directory if it does not exist', async () => {
    const nestedPath = join(testDir, 'nested', 'dir', 'schema.ts')

    mockFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve(createSchemaDoc([])),
    })

    await generateSchema({
      host: 'https://api.example.com',
      output: nestedPath,
    })

    expect(existsSync(nestedPath)).toBe(true)
  })

  it('should throw on HTTP error', async () => {
    mockFetch.mockResolvedValue({
      ok: false,
      status: 500,
      statusText: 'Internal Server Error',
    })

    await expect(
      generateSchema({
        host: 'https://api.example.com',
        output: outputPath,
      }),
    ).rejects.toThrow('HTTP 500: Internal Server Error')
  })

  it('should throw on invalid response', async () => {
    mockFetch.mockResolvedValue({
      ok: true,
      json: () => Promise.resolve({ type: 'unknown' }),
    })

    await expect(
      generateSchema({
        host: 'https://api.example.com',
        output: outputPath,
      }),
    ).rejects.toThrow('Invalid response: missing commands array')
  })

  it('should handle commands without schemas', async () => {
    mockFetch.mockResolvedValue({
      ok: true,
      json: () =>
        Promise.resolve(
          createSchemaDoc([
            {
              id: 'simple.command',
              description: 'A simple command without schemas',
            },
          ]),
        ),
    })

    await generateSchema({
      host: 'https://api.example.com',
      output: outputPath,
    })

    const content = readFileSync(outputPath, 'utf-8')
    expect(content).toContain("'simple.command': {")
    expect(content).toContain('description: "A simple command without schemas"')
    // Should not contain request/response for commands without schemas
    expect(content).not.toContain('request:')
    expect(content).not.toContain('response:')
  })
})
