import type { BrowserWindow } from 'electron'
import { app } from 'electron'

import { ChannelIDs } from '@examples/electron-core'

import { WindowManager } from './windows-manager'

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const APP_WINDOW_WEBPACK_ENTRY: string
declare const WORKER_WINDOW_WEBPACK_ENTRY: string
declare const SANDBOX_WINDOW_WEBPACK_ENTRY: string

/**
 * Create all the windows for the application.
 */
export function createWindows() {
  if (!WindowManager.has(ChannelIDs.WORKER)) {
    // Create Worker Window
    WindowManager.createProcessWindow({
      id: ChannelIDs.WORKER,
      url: WORKER_WINDOW_WEBPACK_ENTRY,
      nodeIntegration: true,
      directIPCChannel: true,
    })
  }

  if (!WindowManager.has(ChannelIDs.SANDBOX)) {
    // Create Sandbox Window
    WindowManager.createProcessWindow({
      id: ChannelIDs.SANDBOX,
      url: SANDBOX_WINDOW_WEBPACK_ENTRY,
      allowedDomains: ['https://api.angelfish.app', 'https://auth.angelfish.app'],
    })
  }

  if (!WindowManager.has(ChannelIDs.APP)) {
    // Create App Window
    createMainAppWindow()
  }
}

/**
 * Create the main application window.
 *
 * @returns   The new {BrowserWindow}
 */
function createMainAppWindow(): BrowserWindow {
  const appWindow = WindowManager.createRendererWindow({
    id: ChannelIDs.APP,
    url: APP_WINDOW_WEBPACK_ENTRY,
    title: 'Frontend',
    width: 900,
    height: 600,
  })

  // Handle MacOS activation to maximize window if minimized
  const maximizeWindow = () => {
    if (appWindow && !appWindow.isDestroyed()) {
      if (appWindow.isMinimized()) {
        appWindow.restore()
      }
      appWindow.show()
      appWindow.focus()
    }
  }
  app.on('activate', maximizeWindow)
  appWindow.on('closed', () => app.removeListener('activate', maximizeWindow))

  return appWindow
}
