import { mkdirSync, writeFileSync } from 'fs'
import { dirname } from 'path'

import { jsonSchemaToValibot } from './schema-converter'
import { fetchSchemas } from './schema-fetcher'

import type { ICommandDefinitionBase } from '../../registry'

export interface GenerateSchemaOptions {
  host: string
  output: string
  prefix?: string
}

/**
 * Generates the variable name from prefix
 * e.g., 'cloud' -> 'CloudCommandSchema'
 * e.g., 'my-api' -> 'MyApiCommandSchema'
 */
function generateSchemaName(prefix?: string): string {
  if (!prefix) {
    return 'RemoteCommandSchema'
  }

  // Convert to PascalCase
  const pascalCase = prefix
    .split(/[-_.]/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('')

  return `${pascalCase}CommandSchema`
}

/**
 * Generates TypeScript code for a single command
 */
function generateCommandCode(cmd: ICommandDefinitionBase, prefix?: string, indent = 1): string {
  const spaces = '  '.repeat(indent)
  const innerSpaces = '  '.repeat(indent + 1)

  // Apply prefix to command ID
  const commandId = prefix ? `${prefix}.${cmd.id}` : cmd.id

  const lines: string[] = []
  lines.push(`${spaces}'${commandId}': {`)

  if (cmd.description) {
    lines.push(`${innerSpaces}description: ${JSON.stringify(cmd.description)},`)
  }

  if (cmd.schema?.request) {
    const requestCode = jsonSchemaToValibot(cmd.schema.request, indent + 1)
    lines.push(`${innerSpaces}request: ${requestCode},`)
  }

  if (cmd.schema?.response) {
    const responseCode = jsonSchemaToValibot(cmd.schema.response, indent + 1)
    lines.push(`${innerSpaces}response: ${responseCode},`)
  }

  lines.push(`${spaces}},`)

  return lines.join('\n')
}

/**
 * Generates the complete TypeScript file content
 */
function generateFileContent(
  commands: ICommandDefinitionBase[],
  options: GenerateSchemaOptions,
): string {
  const schemaName = generateSchemaName(options.prefix)
  const lines: string[] = []

  // Header
  lines.push('// Auto-generated by cmd-ipc CLI - DO NOT EDIT')
  lines.push(`// Generated from: ${options.host}/cmds.json`)
  lines.push(`// Generated at: ${new Date().toISOString()}`)
  lines.push('')
  lines.push("import * as v from 'valibot'")
  lines.push('')
  lines.push("import type { CommandSchemaMap } from '@coralstack/cmd-ipc'")
  lines.push('')

  // Schema object
  lines.push(`export const ${schemaName} = {`)

  for (const cmd of commands) {
    lines.push(generateCommandCode(cmd, options.prefix))
  }

  lines.push('} as const satisfies CommandSchemaMap')
  lines.push('')

  return lines.join('\n')
}

/**
 * Main function to generate schema from a remote server
 */
export async function generateSchema(options: GenerateSchemaOptions): Promise<void> {
  // Fetch schemas from server
  const commands = await fetchSchemas({
    host: options.host,
  })

  if (commands.length === 0) {
    // eslint-disable-next-line no-console
    console.warn('Warning: No commands returned from server')
  }

  // Generate TypeScript content
  const content = generateFileContent(commands, options)

  // Ensure output directory exists
  const outputDir = dirname(options.output)
  mkdirSync(outputDir, { recursive: true })

  // Write file
  writeFileSync(options.output, content, 'utf-8')
}
